20250423 update1

diff --git a/Dockerfile.env b/Dockerfile.env
--- a/Dockerfile.env
+++ b/Dockerfile.env
@@ -1,22 +1,31 @@
-FROM denoland/deno:2.2.6
+FROM denoland/deno:2.2.10
 
 # Setup Environment
 WORKDIR /app
 ENV NODE_ENV=production
 
-# Copy Project Source Code  
+# Setup Project
 COPY . .
-
-# Building Static Site
-RUN deno task install && deno task build 
-
-# Find Site Page
 RUN mkdir -p public/pagefind
-RUN deno task pagefind && ls -l dist/pagefind
-RUN cp -r dist/pagefind/* public/pagefind/
 
-# Service Start 
+# Build Project
+RUN deno task install && deno task build
+
+# Find Pages Index
+RUN deno task pagefind
+RUN ls -la dist/pagefind || echo "Failed to create pagefind index"
+RUN if [ -d "dist/pagefind" ]; then \
+      cp -r dist/pagefind/* public/pagefind/; \
+    else \
+      echo "Pagefind index not created properly"; \
+      exit 1; \
+    fi
+
+# Rebuild Project
+RUN deno task build
+
+# Service Start
 CMD ["deno", "task", "serve"]
 
-# Listens Serve  Port
+# Listens Serve Port
 EXPOSE 8085
